//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::CoreFoundation::*;

pub type CGFloat = c_double;

extern_struct!(
    pub struct CGPoint {
        pub x: CGFloat,
        pub y: CGFloat,
    }
);

extern_struct!(
    pub struct CGSize {
        pub width: CGFloat,
        pub height: CGFloat,
    }
);

extern_struct!(
    pub struct CGVector {
        pub dx: CGFloat,
        pub dy: CGFloat,
    }
);

extern_struct!(
    pub struct CGRect {
        pub origin: CGPoint,
        pub size: CGSize,
    }
);

ns_closed_enum!(
    #[underlying(u32)]
    pub enum CGRectEdge {
        CGRectMinXEdge = 0,
        CGRectMinYEdge = 1,
        CGRectMaxXEdge = 2,
        CGRectMaxYEdge = 3,
    }
);

extern_struct!(
    pub struct CGAffineTransform {
        pub a: CGFloat,
        pub b: CGFloat,
        pub c: CGFloat,
        pub d: CGFloat,
        pub tx: CGFloat,
        pub ty: CGFloat,
    }
);

extern_struct!(
    pub struct CGAffineTransformComponents {
        pub scale: CGSize,
        pub horizontalShear: CGFloat,
        pub rotation: CGFloat,
        pub translation: CGVector,
    }
);
