//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::CoreAudioTypes::*;

pub type AVAudioInteger = c_long;

pub type AVAudioUInteger = c_ulong;

pub type AudioSessionID = u32;

ns_enum!(
    #[underlying(AVAudioInteger)]
    pub enum AVAudioSessionErrorCode {
        AVAudioSessionErrorCodeNone = 0,
        AVAudioSessionErrorCodeMediaServicesFailed = 1836282486,
        AVAudioSessionErrorCodeIsBusy = 560030580,
        AVAudioSessionErrorCodeIncompatibleCategory = 560161140,
        AVAudioSessionErrorCodeCannotInterruptOthers = 560557684,
        AVAudioSessionErrorCodeMissingEntitlement = 1701737535,
        AVAudioSessionErrorCodeSiriIsRecording = 1936290409,
        AVAudioSessionErrorCodeCannotStartPlaying = 561015905,
        AVAudioSessionErrorCodeCannotStartRecording = 561145187,
        AVAudioSessionErrorCodeBadParam = -50,
        AVAudioSessionErrorCodeInsufficientPriority = 561017449,
        AVAudioSessionErrorCodeResourceNotAvailable = 561145203,
        AVAudioSessionErrorCodeUnspecified = 2003329396,
        AVAudioSessionErrorCodeExpiredSession = 561210739,
        AVAudioSessionErrorCodeSessionNotActive = 1768841571,
    }
);
