//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::CoreAudioTypes::*;

ns_enum!(
    #[underlying(OSStatus)]
    pub enum __anonymous__ {
        kAudio_UnimplementedError = -4,
        kAudio_FileNotFoundError = -43,
        kAudio_FilePermissionError = -54,
        kAudio_TooManyFilesOpenError = -42,
        kAudio_BadFilePathError = 561017960,
        kAudio_ParamError = -50,
        kAudio_MemFullError = -108,
    }
);

extern_struct!(
    pub struct AudioValueRange {
        pub mMinimum: f64,
        pub mMaximum: f64,
    }
);

extern_struct!(
    pub struct AudioValueTranslation {
        pub mInputData: NonNull<c_void>,
        pub mInputDataSize: u32,
        pub mOutputData: NonNull<c_void>,
        pub mOutputDataSize: u32,
    }
);

extern_struct!(
    pub struct AudioBuffer {
        pub mNumberChannels: u32,
        pub mDataByteSize: u32,
        pub mData: *mut c_void,
    }
);

extern_struct!(
    pub struct AudioBufferList {
        pub mNumberBuffers: u32,
        pub mBuffers: [AudioBuffer; 1],
    }
);

pub type AudioSampleType = f32;

pub type AudioUnitSampleType = f32;

pub type AudioFormatID = u32;

pub type AudioFormatFlags = u32;

extern_struct!(
    pub struct AudioStreamBasicDescription {
        pub mSampleRate: f64,
        pub mFormatID: AudioFormatID,
        pub mFormatFlags: AudioFormatFlags,
        pub mBytesPerPacket: u32,
        pub mFramesPerPacket: u32,
        pub mBytesPerFrame: u32,
        pub mChannelsPerFrame: u32,
        pub mBitsPerChannel: u32,
        pub mReserved: u32,
    }
);

extern_static!(kAudioStreamAnyRate: f64 = 0.0);

ns_enum!(
    #[underlying(AudioFormatID)]
    pub enum __anonymous__ {
        kAudioFormatLinearPCM = 1819304813,
        kAudioFormatAC3 = 1633889587,
        kAudioFormat60958AC3 = 1667326771,
        kAudioFormatAppleIMA4 = 1768775988,
        kAudioFormatMPEG4AAC = 1633772320,
        kAudioFormatMPEG4CELP = 1667591280,
        kAudioFormatMPEG4HVXC = 1752594531,
        kAudioFormatMPEG4TwinVQ = 1953986161,
        kAudioFormatMACE3 = 1296122675,
        kAudioFormatMACE6 = 1296122678,
        kAudioFormatULaw = 1970037111,
        kAudioFormatALaw = 1634492791,
        kAudioFormatQDesign = 1363430723,
        kAudioFormatQDesign2 = 1363430706,
        kAudioFormatQUALCOMM = 1365470320,
        kAudioFormatMPEGLayer1 = 778924081,
        kAudioFormatMPEGLayer2 = 778924082,
        kAudioFormatMPEGLayer3 = 778924083,
        kAudioFormatTimeCode = 1953066341,
        kAudioFormatMIDIStream = 1835623529,
        kAudioFormatParameterValueStream = 1634760307,
        kAudioFormatAppleLossless = 1634492771,
        kAudioFormatMPEG4AAC_HE = 1633772392,
        kAudioFormatMPEG4AAC_LD = 1633772396,
        kAudioFormatMPEG4AAC_ELD = 1633772389,
        kAudioFormatMPEG4AAC_ELD_SBR = 1633772390,
        kAudioFormatMPEG4AAC_ELD_V2 = 1633772391,
        kAudioFormatMPEG4AAC_HE_V2 = 1633772400,
        kAudioFormatMPEG4AAC_Spatial = 1633772403,
        kAudioFormatMPEGD_USAC = 1970495843,
        kAudioFormatAMR = 1935764850,
        kAudioFormatAMR_WB = 1935767394,
        kAudioFormatAudible = 1096107074,
        kAudioFormatiLBC = 1768710755,
        kAudioFormatDVIIntelIMA = 0x6D730011,
        kAudioFormatMicrosoftGSM = 0x6D730031,
        kAudioFormatAES3 = 1634038579,
        kAudioFormatEnhancedAC3 = 1700998451,
        kAudioFormatFLAC = 1718378851,
        kAudioFormatOpus = 1869641075,
    }
);

ns_enum!(
    #[underlying(AudioFormatFlags)]
    pub enum __anonymous__ {
        kAudioFormatFlagIsFloat = 1 << 0,
        kAudioFormatFlagIsBigEndian = 1 << 1,
        kAudioFormatFlagIsSignedInteger = 1 << 2,
        kAudioFormatFlagIsPacked = 1 << 3,
        kAudioFormatFlagIsAlignedHigh = 1 << 4,
        kAudioFormatFlagIsNonInterleaved = 1 << 5,
        kAudioFormatFlagIsNonMixable = 1 << 6,
        kAudioFormatFlagsAreAllClear = 0x80000000,
        kLinearPCMFormatFlagIsFloat = kAudioFormatFlagIsFloat,
        kLinearPCMFormatFlagIsBigEndian = kAudioFormatFlagIsBigEndian,
        kLinearPCMFormatFlagIsSignedInteger = kAudioFormatFlagIsSignedInteger,
        kLinearPCMFormatFlagIsPacked = kAudioFormatFlagIsPacked,
        kLinearPCMFormatFlagIsAlignedHigh = kAudioFormatFlagIsAlignedHigh,
        kLinearPCMFormatFlagIsNonInterleaved = kAudioFormatFlagIsNonInterleaved,
        kLinearPCMFormatFlagIsNonMixable = kAudioFormatFlagIsNonMixable,
        kLinearPCMFormatFlagsSampleFractionShift = 7,
        kLinearPCMFormatFlagsSampleFractionMask = 0x3F << kLinearPCMFormatFlagsSampleFractionShift,
        kLinearPCMFormatFlagsAreAllClear = kAudioFormatFlagsAreAllClear,
        kAppleLosslessFormatFlag_16BitSourceData = 1,
        kAppleLosslessFormatFlag_20BitSourceData = 2,
        kAppleLosslessFormatFlag_24BitSourceData = 3,
        kAppleLosslessFormatFlag_32BitSourceData = 4,
    }
);

ns_enum!(
    #[underlying(AudioFormatFlags)]
    pub enum __anonymous__ {
        kAudioFormatFlagsNativeEndian = 0,
        kAudioFormatFlagsCanonical =
            kAudioFormatFlagIsFloat | kAudioFormatFlagsNativeEndian | kAudioFormatFlagIsPacked,
        kAudioFormatFlagsAudioUnitCanonical = kAudioFormatFlagIsFloat
            | kAudioFormatFlagsNativeEndian
            | kAudioFormatFlagIsPacked
            | kAudioFormatFlagIsNonInterleaved,
        kAudioFormatFlagsNativeFloatPacked =
            kAudioFormatFlagIsFloat | kAudioFormatFlagsNativeEndian | kAudioFormatFlagIsPacked,
    }
);

extern_struct!(
    pub struct AudioStreamPacketDescription {
        pub mStartOffset: i64,
        pub mVariableFramesInPacket: u32,
        pub mDataByteSize: u32,
    }
);

ns_enum!(
    #[underlying(u32)]
    pub enum SMPTETimeType {
        kSMPTETimeType24 = 0,
        kSMPTETimeType25 = 1,
        kSMPTETimeType30Drop = 2,
        kSMPTETimeType30 = 3,
        kSMPTETimeType2997 = 4,
        kSMPTETimeType2997Drop = 5,
        kSMPTETimeType60 = 6,
        kSMPTETimeType5994 = 7,
        kSMPTETimeType60Drop = 8,
        kSMPTETimeType5994Drop = 9,
        kSMPTETimeType50 = 10,
        kSMPTETimeType2398 = 11,
    }
);

ns_options!(
    #[underlying(u32)]
    pub enum SMPTETimeFlags {
        kSMPTETimeUnknown = 0,
        kSMPTETimeValid = 1 << 0,
        kSMPTETimeRunning = 1 << 1,
    }
);

extern_struct!(
    pub struct SMPTETime {
        pub mSubframes: i16,
        pub mSubframeDivisor: i16,
        pub mCounter: u32,
        pub mType: SMPTETimeType,
        pub mFlags: SMPTETimeFlags,
        pub mHours: i16,
        pub mMinutes: i16,
        pub mSeconds: i16,
        pub mFrames: i16,
    }
);

ns_options!(
    #[underlying(u32)]
    pub enum AudioTimeStampFlags {
        kAudioTimeStampNothingValid = 0,
        kAudioTimeStampSampleTimeValid = 1 << 0,
        kAudioTimeStampHostTimeValid = 1 << 1,
        kAudioTimeStampRateScalarValid = 1 << 2,
        kAudioTimeStampWordClockTimeValid = 1 << 3,
        kAudioTimeStampSMPTETimeValid = 1 << 4,
        kAudioTimeStampSampleHostTimeValid =
            kAudioTimeStampSampleTimeValid | kAudioTimeStampHostTimeValid,
    }
);

extern_struct!(
    pub struct AudioTimeStamp {
        pub mSampleTime: f64,
        pub mHostTime: u64,
        pub mRateScalar: f64,
        pub mWordClockTime: u64,
        pub mSMPTETime: SMPTETime,
        pub mFlags: AudioTimeStampFlags,
        pub mReserved: u32,
    }
);

extern_struct!(
    pub struct AudioClassDescription {
        pub mType: OSType,
        pub mSubType: OSType,
        pub mManufacturer: OSType,
    }
);

pub type AudioChannelLabel = u32;

pub type AudioChannelLayoutTag = u32;

ns_enum!(
    #[underlying(AudioChannelLabel)]
    pub enum __anonymous__ {
        kAudioChannelLabel_Unknown = 0xFFFFFFFF,
        kAudioChannelLabel_Unused = 0,
        kAudioChannelLabel_UseCoordinates = 100,
        kAudioChannelLabel_Left = 1,
        kAudioChannelLabel_Right = 2,
        kAudioChannelLabel_Center = 3,
        kAudioChannelLabel_LFEScreen = 4,
        kAudioChannelLabel_LeftSurround = 5,
        kAudioChannelLabel_RightSurround = 6,
        kAudioChannelLabel_LeftCenter = 7,
        kAudioChannelLabel_RightCenter = 8,
        kAudioChannelLabel_CenterSurround = 9,
        kAudioChannelLabel_LeftSurroundDirect = 10,
        kAudioChannelLabel_RightSurroundDirect = 11,
        kAudioChannelLabel_TopCenterSurround = 12,
        kAudioChannelLabel_VerticalHeightLeft = 13,
        kAudioChannelLabel_VerticalHeightCenter = 14,
        kAudioChannelLabel_VerticalHeightRight = 15,
        kAudioChannelLabel_TopBackLeft = 16,
        kAudioChannelLabel_TopBackCenter = 17,
        kAudioChannelLabel_TopBackRight = 18,
        kAudioChannelLabel_RearSurroundLeft = 33,
        kAudioChannelLabel_RearSurroundRight = 34,
        kAudioChannelLabel_LeftWide = 35,
        kAudioChannelLabel_RightWide = 36,
        kAudioChannelLabel_LFE2 = 37,
        kAudioChannelLabel_LeftTotal = 38,
        kAudioChannelLabel_RightTotal = 39,
        kAudioChannelLabel_HearingImpaired = 40,
        kAudioChannelLabel_Narration = 41,
        kAudioChannelLabel_Mono = 42,
        kAudioChannelLabel_DialogCentricMix = 43,
        kAudioChannelLabel_CenterSurroundDirect = 44,
        kAudioChannelLabel_Haptic = 45,
        kAudioChannelLabel_LeftTopFront = kAudioChannelLabel_VerticalHeightLeft,
        kAudioChannelLabel_CenterTopFront = kAudioChannelLabel_VerticalHeightCenter,
        kAudioChannelLabel_RightTopFront = kAudioChannelLabel_VerticalHeightRight,
        kAudioChannelLabel_LeftTopMiddle = 49,
        kAudioChannelLabel_CenterTopMiddle = kAudioChannelLabel_TopCenterSurround,
        kAudioChannelLabel_RightTopMiddle = 51,
        kAudioChannelLabel_LeftTopRear = 52,
        kAudioChannelLabel_CenterTopRear = 53,
        kAudioChannelLabel_RightTopRear = 54,
        kAudioChannelLabel_LeftSideSurround = 55,
        kAudioChannelLabel_RightSideSurround = 56,
        kAudioChannelLabel_LeftBottom = 57,
        kAudioChannelLabel_RightBottom = 58,
        kAudioChannelLabel_CenterBottom = 59,
        kAudioChannelLabel_LeftTopSurround = 60,
        kAudioChannelLabel_RightTopSurround = 61,
        kAudioChannelLabel_LFE3 = 62,
        kAudioChannelLabel_LeftBackSurround = 63,
        kAudioChannelLabel_RightBackSurround = 64,
        kAudioChannelLabel_LeftEdgeOfScreen = 65,
        kAudioChannelLabel_RightEdgeOfScreen = 66,
        kAudioChannelLabel_Ambisonic_W = 200,
        kAudioChannelLabel_Ambisonic_X = 201,
        kAudioChannelLabel_Ambisonic_Y = 202,
        kAudioChannelLabel_Ambisonic_Z = 203,
        kAudioChannelLabel_MS_Mid = 204,
        kAudioChannelLabel_MS_Side = 205,
        kAudioChannelLabel_XY_X = 206,
        kAudioChannelLabel_XY_Y = 207,
        kAudioChannelLabel_BinauralLeft = 208,
        kAudioChannelLabel_BinauralRight = 209,
        kAudioChannelLabel_HeadphonesLeft = 301,
        kAudioChannelLabel_HeadphonesRight = 302,
        kAudioChannelLabel_ClickTrack = 304,
        kAudioChannelLabel_ForeignLanguage = 305,
        kAudioChannelLabel_Discrete = 400,
        kAudioChannelLabel_Discrete_0 = (1 << 16) | 0,
        kAudioChannelLabel_Discrete_1 = (1 << 16) | 1,
        kAudioChannelLabel_Discrete_2 = (1 << 16) | 2,
        kAudioChannelLabel_Discrete_3 = (1 << 16) | 3,
        kAudioChannelLabel_Discrete_4 = (1 << 16) | 4,
        kAudioChannelLabel_Discrete_5 = (1 << 16) | 5,
        kAudioChannelLabel_Discrete_6 = (1 << 16) | 6,
        kAudioChannelLabel_Discrete_7 = (1 << 16) | 7,
        kAudioChannelLabel_Discrete_8 = (1 << 16) | 8,
        kAudioChannelLabel_Discrete_9 = (1 << 16) | 9,
        kAudioChannelLabel_Discrete_10 = (1 << 16) | 10,
        kAudioChannelLabel_Discrete_11 = (1 << 16) | 11,
        kAudioChannelLabel_Discrete_12 = (1 << 16) | 12,
        kAudioChannelLabel_Discrete_13 = (1 << 16) | 13,
        kAudioChannelLabel_Discrete_14 = (1 << 16) | 14,
        kAudioChannelLabel_Discrete_15 = (1 << 16) | 15,
        kAudioChannelLabel_Discrete_65535 = (1 << 16) | 65535,
        kAudioChannelLabel_HOA_ACN = 500,
        kAudioChannelLabel_HOA_ACN_0 = (2 << 16) | 0,
        kAudioChannelLabel_HOA_ACN_1 = (2 << 16) | 1,
        kAudioChannelLabel_HOA_ACN_2 = (2 << 16) | 2,
        kAudioChannelLabel_HOA_ACN_3 = (2 << 16) | 3,
        kAudioChannelLabel_HOA_ACN_4 = (2 << 16) | 4,
        kAudioChannelLabel_HOA_ACN_5 = (2 << 16) | 5,
        kAudioChannelLabel_HOA_ACN_6 = (2 << 16) | 6,
        kAudioChannelLabel_HOA_ACN_7 = (2 << 16) | 7,
        kAudioChannelLabel_HOA_ACN_8 = (2 << 16) | 8,
        kAudioChannelLabel_HOA_ACN_9 = (2 << 16) | 9,
        kAudioChannelLabel_HOA_ACN_10 = (2 << 16) | 10,
        kAudioChannelLabel_HOA_ACN_11 = (2 << 16) | 11,
        kAudioChannelLabel_HOA_ACN_12 = (2 << 16) | 12,
        kAudioChannelLabel_HOA_ACN_13 = (2 << 16) | 13,
        kAudioChannelLabel_HOA_ACN_14 = (2 << 16) | 14,
        kAudioChannelLabel_HOA_ACN_15 = (2 << 16) | 15,
        kAudioChannelLabel_HOA_ACN_65024 = (2 << 16) | 65024,
        kAudioChannelLabel_HOA_SN3D = kAudioChannelLabel_HOA_ACN_0,
        kAudioChannelLabel_HOA_N3D = 3 << 16,
        kAudioChannelLabel_Object = 4 << 16,
        kAudioChannelLabel_BeginReserved = 0xF0000000,
        kAudioChannelLabel_EndReserved = 0xFFFFFFFE,
    }
);

ns_options!(
    #[underlying(u32)]
    pub enum AudioChannelBitmap {
        kAudioChannelBit_Left = 1 << 0,
        kAudioChannelBit_Right = 1 << 1,
        kAudioChannelBit_Center = 1 << 2,
        kAudioChannelBit_LFEScreen = 1 << 3,
        kAudioChannelBit_LeftSurround = 1 << 4,
        kAudioChannelBit_RightSurround = 1 << 5,
        kAudioChannelBit_LeftCenter = 1 << 6,
        kAudioChannelBit_RightCenter = 1 << 7,
        kAudioChannelBit_CenterSurround = 1 << 8,
        kAudioChannelBit_LeftSurroundDirect = 1 << 9,
        kAudioChannelBit_RightSurroundDirect = 1 << 10,
        kAudioChannelBit_TopCenterSurround = 1 << 11,
        kAudioChannelBit_VerticalHeightLeft = 1 << 12,
        kAudioChannelBit_VerticalHeightCenter = 1 << 13,
        kAudioChannelBit_VerticalHeightRight = 1 << 14,
        kAudioChannelBit_TopBackLeft = 1 << 15,
        kAudioChannelBit_TopBackCenter = 1 << 16,
        kAudioChannelBit_TopBackRight = 1 << 17,
        kAudioChannelBit_LeftTopFront = kAudioChannelBit_VerticalHeightLeft,
        kAudioChannelBit_CenterTopFront = kAudioChannelBit_VerticalHeightCenter,
        kAudioChannelBit_RightTopFront = kAudioChannelBit_VerticalHeightRight,
        kAudioChannelBit_LeftTopMiddle = 1 << 21,
        kAudioChannelBit_CenterTopMiddle = kAudioChannelBit_TopCenterSurround,
        kAudioChannelBit_RightTopMiddle = 1 << 23,
        kAudioChannelBit_LeftTopRear = 1 << 24,
        kAudioChannelBit_CenterTopRear = 1 << 25,
        kAudioChannelBit_RightTopRear = 1 << 26,
    }
);

ns_options!(
    #[underlying(u32)]
    pub enum AudioChannelFlags {
        kAudioChannelFlags_AllOff = 0,
        kAudioChannelFlags_RectangularCoordinates = 1 << 0,
        kAudioChannelFlags_SphericalCoordinates = 1 << 1,
        kAudioChannelFlags_Meters = 1 << 2,
    }
);

ns_enum!(
    #[underlying(u32)]
    pub enum AudioChannelCoordinateIndex {
        kAudioChannelCoordinates_LeftRight = 0,
        kAudioChannelCoordinates_BackFront = 1,
        kAudioChannelCoordinates_DownUp = 2,
        kAudioChannelCoordinates_Azimuth = 0,
        kAudioChannelCoordinates_Elevation = 1,
        kAudioChannelCoordinates_Distance = 2,
    }
);

ns_enum!(
    #[underlying(AudioChannelLayoutTag)]
    pub enum __anonymous__ {
        kAudioChannelLayoutTag_UseChannelDescriptions = (0 << 16) | 0,
        kAudioChannelLayoutTag_UseChannelBitmap = (1 << 16) | 0,
        kAudioChannelLayoutTag_Mono = (100 << 16) | 1,
        kAudioChannelLayoutTag_Stereo = (101 << 16) | 2,
        kAudioChannelLayoutTag_StereoHeadphones = (102 << 16) | 2,
        kAudioChannelLayoutTag_MatrixStereo = (103 << 16) | 2,
        kAudioChannelLayoutTag_MidSide = (104 << 16) | 2,
        kAudioChannelLayoutTag_XY = (105 << 16) | 2,
        kAudioChannelLayoutTag_Binaural = (106 << 16) | 2,
        kAudioChannelLayoutTag_Ambisonic_B_Format = (107 << 16) | 4,
        kAudioChannelLayoutTag_Quadraphonic = (108 << 16) | 4,
        kAudioChannelLayoutTag_Pentagonal = (109 << 16) | 5,
        kAudioChannelLayoutTag_Hexagonal = (110 << 16) | 6,
        kAudioChannelLayoutTag_Octagonal = (111 << 16) | 8,
        kAudioChannelLayoutTag_Cube = (112 << 16) | 8,
        kAudioChannelLayoutTag_MPEG_1_0 = kAudioChannelLayoutTag_Mono,
        kAudioChannelLayoutTag_MPEG_2_0 = kAudioChannelLayoutTag_Stereo,
        kAudioChannelLayoutTag_MPEG_3_0_A = (113 << 16) | 3,
        kAudioChannelLayoutTag_MPEG_3_0_B = (114 << 16) | 3,
        kAudioChannelLayoutTag_MPEG_4_0_A = (115 << 16) | 4,
        kAudioChannelLayoutTag_MPEG_4_0_B = (116 << 16) | 4,
        kAudioChannelLayoutTag_MPEG_5_0_A = (117 << 16) | 5,
        kAudioChannelLayoutTag_MPEG_5_0_B = (118 << 16) | 5,
        kAudioChannelLayoutTag_MPEG_5_0_C = (119 << 16) | 5,
        kAudioChannelLayoutTag_MPEG_5_0_D = (120 << 16) | 5,
        kAudioChannelLayoutTag_MPEG_5_1_A = (121 << 16) | 6,
        kAudioChannelLayoutTag_MPEG_5_1_B = (122 << 16) | 6,
        kAudioChannelLayoutTag_MPEG_5_1_C = (123 << 16) | 6,
        kAudioChannelLayoutTag_MPEG_5_1_D = (124 << 16) | 6,
        kAudioChannelLayoutTag_MPEG_6_1_A = (125 << 16) | 7,
        kAudioChannelLayoutTag_MPEG_7_1_A = (126 << 16) | 8,
        kAudioChannelLayoutTag_MPEG_7_1_B = (127 << 16) | 8,
        kAudioChannelLayoutTag_MPEG_7_1_C = (128 << 16) | 8,
        kAudioChannelLayoutTag_Emagic_Default_7_1 = (129 << 16) | 8,
        kAudioChannelLayoutTag_SMPTE_DTV = (130 << 16) | 8,
        kAudioChannelLayoutTag_ITU_1_0 = kAudioChannelLayoutTag_Mono,
        kAudioChannelLayoutTag_ITU_2_0 = kAudioChannelLayoutTag_Stereo,
        kAudioChannelLayoutTag_ITU_2_1 = (131 << 16) | 3,
        kAudioChannelLayoutTag_ITU_2_2 = (132 << 16) | 4,
        kAudioChannelLayoutTag_ITU_3_0 = kAudioChannelLayoutTag_MPEG_3_0_A,
        kAudioChannelLayoutTag_ITU_3_1 = kAudioChannelLayoutTag_MPEG_4_0_A,
        kAudioChannelLayoutTag_ITU_3_2 = kAudioChannelLayoutTag_MPEG_5_0_A,
        kAudioChannelLayoutTag_ITU_3_2_1 = kAudioChannelLayoutTag_MPEG_5_1_A,
        kAudioChannelLayoutTag_ITU_3_4_1 = kAudioChannelLayoutTag_MPEG_7_1_C,
        kAudioChannelLayoutTag_DVD_0 = kAudioChannelLayoutTag_Mono,
        kAudioChannelLayoutTag_DVD_1 = kAudioChannelLayoutTag_Stereo,
        kAudioChannelLayoutTag_DVD_2 = kAudioChannelLayoutTag_ITU_2_1,
        kAudioChannelLayoutTag_DVD_3 = kAudioChannelLayoutTag_ITU_2_2,
        kAudioChannelLayoutTag_DVD_4 = (133 << 16) | 3,
        kAudioChannelLayoutTag_DVD_5 = (134 << 16) | 4,
        kAudioChannelLayoutTag_DVD_6 = (135 << 16) | 5,
        kAudioChannelLayoutTag_DVD_7 = kAudioChannelLayoutTag_MPEG_3_0_A,
        kAudioChannelLayoutTag_DVD_8 = kAudioChannelLayoutTag_MPEG_4_0_A,
        kAudioChannelLayoutTag_DVD_9 = kAudioChannelLayoutTag_MPEG_5_0_A,
        kAudioChannelLayoutTag_DVD_10 = (136 << 16) | 4,
        kAudioChannelLayoutTag_DVD_11 = (137 << 16) | 5,
        kAudioChannelLayoutTag_DVD_12 = kAudioChannelLayoutTag_MPEG_5_1_A,
        kAudioChannelLayoutTag_DVD_13 = kAudioChannelLayoutTag_DVD_8,
        kAudioChannelLayoutTag_DVD_14 = kAudioChannelLayoutTag_DVD_9,
        kAudioChannelLayoutTag_DVD_15 = kAudioChannelLayoutTag_DVD_10,
        kAudioChannelLayoutTag_DVD_16 = kAudioChannelLayoutTag_DVD_11,
        kAudioChannelLayoutTag_DVD_17 = kAudioChannelLayoutTag_DVD_12,
        kAudioChannelLayoutTag_DVD_18 = (138 << 16) | 5,
        kAudioChannelLayoutTag_DVD_19 = kAudioChannelLayoutTag_MPEG_5_0_B,
        kAudioChannelLayoutTag_DVD_20 = kAudioChannelLayoutTag_MPEG_5_1_B,
        kAudioChannelLayoutTag_AudioUnit_4 = kAudioChannelLayoutTag_Quadraphonic,
        kAudioChannelLayoutTag_AudioUnit_5 = kAudioChannelLayoutTag_Pentagonal,
        kAudioChannelLayoutTag_AudioUnit_6 = kAudioChannelLayoutTag_Hexagonal,
        kAudioChannelLayoutTag_AudioUnit_8 = kAudioChannelLayoutTag_Octagonal,
        kAudioChannelLayoutTag_AudioUnit_5_0 = kAudioChannelLayoutTag_MPEG_5_0_B,
        kAudioChannelLayoutTag_AudioUnit_6_0 = (139 << 16) | 6,
        kAudioChannelLayoutTag_AudioUnit_7_0 = (140 << 16) | 7,
        kAudioChannelLayoutTag_AudioUnit_7_0_Front = (148 << 16) | 7,
        kAudioChannelLayoutTag_AudioUnit_5_1 = kAudioChannelLayoutTag_MPEG_5_1_A,
        kAudioChannelLayoutTag_AudioUnit_6_1 = kAudioChannelLayoutTag_MPEG_6_1_A,
        kAudioChannelLayoutTag_AudioUnit_7_1 = kAudioChannelLayoutTag_MPEG_7_1_C,
        kAudioChannelLayoutTag_AudioUnit_7_1_Front = kAudioChannelLayoutTag_MPEG_7_1_A,
        kAudioChannelLayoutTag_AAC_3_0 = kAudioChannelLayoutTag_MPEG_3_0_B,
        kAudioChannelLayoutTag_AAC_Quadraphonic = kAudioChannelLayoutTag_Quadraphonic,
        kAudioChannelLayoutTag_AAC_4_0 = kAudioChannelLayoutTag_MPEG_4_0_B,
        kAudioChannelLayoutTag_AAC_5_0 = kAudioChannelLayoutTag_MPEG_5_0_D,
        kAudioChannelLayoutTag_AAC_5_1 = kAudioChannelLayoutTag_MPEG_5_1_D,
        kAudioChannelLayoutTag_AAC_6_0 = (141 << 16) | 6,
        kAudioChannelLayoutTag_AAC_6_1 = (142 << 16) | 7,
        kAudioChannelLayoutTag_AAC_7_0 = (143 << 16) | 7,
        kAudioChannelLayoutTag_AAC_7_1 = kAudioChannelLayoutTag_MPEG_7_1_B,
        kAudioChannelLayoutTag_AAC_7_1_B = (183 << 16) | 8,
        kAudioChannelLayoutTag_AAC_7_1_C = (184 << 16) | 8,
        kAudioChannelLayoutTag_AAC_Octagonal = (144 << 16) | 8,
        kAudioChannelLayoutTag_TMH_10_2_std = (145 << 16) | 16,
        kAudioChannelLayoutTag_TMH_10_2_full = (146 << 16) | 21,
        kAudioChannelLayoutTag_AC3_1_0_1 = (149 << 16) | 2,
        kAudioChannelLayoutTag_AC3_3_0 = (150 << 16) | 3,
        kAudioChannelLayoutTag_AC3_3_1 = (151 << 16) | 4,
        kAudioChannelLayoutTag_AC3_3_0_1 = (152 << 16) | 4,
        kAudioChannelLayoutTag_AC3_2_1_1 = (153 << 16) | 4,
        kAudioChannelLayoutTag_AC3_3_1_1 = (154 << 16) | 5,
        kAudioChannelLayoutTag_EAC_6_0_A = (155 << 16) | 6,
        kAudioChannelLayoutTag_EAC_7_0_A = (156 << 16) | 7,
        kAudioChannelLayoutTag_EAC3_6_1_A = (157 << 16) | 7,
        kAudioChannelLayoutTag_EAC3_6_1_B = (158 << 16) | 7,
        kAudioChannelLayoutTag_EAC3_6_1_C = (159 << 16) | 7,
        kAudioChannelLayoutTag_EAC3_7_1_A = (160 << 16) | 8,
        kAudioChannelLayoutTag_EAC3_7_1_B = (161 << 16) | 8,
        kAudioChannelLayoutTag_EAC3_7_1_C = (162 << 16) | 8,
        kAudioChannelLayoutTag_EAC3_7_1_D = (163 << 16) | 8,
        kAudioChannelLayoutTag_EAC3_7_1_E = (164 << 16) | 8,
        kAudioChannelLayoutTag_EAC3_7_1_F = (165 << 16) | 8,
        kAudioChannelLayoutTag_EAC3_7_1_G = (166 << 16) | 8,
        kAudioChannelLayoutTag_EAC3_7_1_H = (167 << 16) | 8,
        kAudioChannelLayoutTag_DTS_3_1 = (168 << 16) | 4,
        kAudioChannelLayoutTag_DTS_4_1 = (169 << 16) | 5,
        kAudioChannelLayoutTag_DTS_6_0_A = (170 << 16) | 6,
        kAudioChannelLayoutTag_DTS_6_0_B = (171 << 16) | 6,
        kAudioChannelLayoutTag_DTS_6_0_C = (172 << 16) | 6,
        kAudioChannelLayoutTag_DTS_6_1_A = (173 << 16) | 7,
        kAudioChannelLayoutTag_DTS_6_1_B = (174 << 16) | 7,
        kAudioChannelLayoutTag_DTS_6_1_C = (175 << 16) | 7,
        kAudioChannelLayoutTag_DTS_7_0 = (176 << 16) | 7,
        kAudioChannelLayoutTag_DTS_7_1 = (177 << 16) | 8,
        kAudioChannelLayoutTag_DTS_8_0_A = (178 << 16) | 8,
        kAudioChannelLayoutTag_DTS_8_0_B = (179 << 16) | 8,
        kAudioChannelLayoutTag_DTS_8_1_A = (180 << 16) | 9,
        kAudioChannelLayoutTag_DTS_8_1_B = (181 << 16) | 9,
        kAudioChannelLayoutTag_DTS_6_1_D = (182 << 16) | 7,
        kAudioChannelLayoutTag_WAVE_2_1 = kAudioChannelLayoutTag_DVD_4,
        kAudioChannelLayoutTag_WAVE_3_0 = kAudioChannelLayoutTag_MPEG_3_0_A,
        kAudioChannelLayoutTag_WAVE_4_0_A = kAudioChannelLayoutTag_ITU_2_2,
        kAudioChannelLayoutTag_WAVE_4_0_B = (185 << 16) | 4,
        kAudioChannelLayoutTag_WAVE_5_0_A = kAudioChannelLayoutTag_MPEG_5_0_A,
        kAudioChannelLayoutTag_WAVE_5_0_B = (186 << 16) | 5,
        kAudioChannelLayoutTag_WAVE_5_1_A = kAudioChannelLayoutTag_MPEG_5_1_A,
        kAudioChannelLayoutTag_WAVE_5_1_B = (187 << 16) | 6,
        kAudioChannelLayoutTag_WAVE_6_1 = (188 << 16) | 7,
        kAudioChannelLayoutTag_WAVE_7_1 = (189 << 16) | 8,
        kAudioChannelLayoutTag_HOA_ACN_SN3D = (190 << 16) | 0,
        kAudioChannelLayoutTag_HOA_ACN_N3D = (191 << 16) | 0,
        kAudioChannelLayoutTag_Atmos_5_1_2 = (194 << 16) | 8,
        kAudioChannelLayoutTag_Atmos_5_1_4 = (195 << 16) | 10,
        kAudioChannelLayoutTag_Atmos_7_1_2 = (196 << 16) | 10,
        kAudioChannelLayoutTag_Atmos_7_1_4 = (192 << 16) | 12,
        kAudioChannelLayoutTag_Atmos_9_1_6 = (193 << 16) | 16,
        kAudioChannelLayoutTag_Logic_Mono = kAudioChannelLayoutTag_Mono,
        kAudioChannelLayoutTag_Logic_Stereo = kAudioChannelLayoutTag_Stereo,
        kAudioChannelLayoutTag_Logic_Quadraphonic = kAudioChannelLayoutTag_Quadraphonic,
        kAudioChannelLayoutTag_Logic_4_0_A = kAudioChannelLayoutTag_MPEG_4_0_A,
        kAudioChannelLayoutTag_Logic_4_0_B = kAudioChannelLayoutTag_MPEG_4_0_B,
        kAudioChannelLayoutTag_Logic_4_0_C = (197 << 16) | 4,
        kAudioChannelLayoutTag_Logic_5_0_A = kAudioChannelLayoutTag_MPEG_5_0_A,
        kAudioChannelLayoutTag_Logic_5_0_B = kAudioChannelLayoutTag_MPEG_5_0_B,
        kAudioChannelLayoutTag_Logic_5_0_C = kAudioChannelLayoutTag_MPEG_5_0_C,
        kAudioChannelLayoutTag_Logic_5_0_D = kAudioChannelLayoutTag_MPEG_5_0_D,
        kAudioChannelLayoutTag_Logic_5_1_A = kAudioChannelLayoutTag_MPEG_5_1_A,
        kAudioChannelLayoutTag_Logic_5_1_B = kAudioChannelLayoutTag_MPEG_5_1_B,
        kAudioChannelLayoutTag_Logic_5_1_C = kAudioChannelLayoutTag_MPEG_5_1_C,
        kAudioChannelLayoutTag_Logic_5_1_D = kAudioChannelLayoutTag_MPEG_5_1_D,
        kAudioChannelLayoutTag_Logic_6_0_A = kAudioChannelLayoutTag_AAC_6_0,
        kAudioChannelLayoutTag_Logic_6_0_B = (198 << 16) | 6,
        kAudioChannelLayoutTag_Logic_6_0_C = kAudioChannelLayoutTag_AudioUnit_6_0,
        kAudioChannelLayoutTag_Logic_6_1_A = kAudioChannelLayoutTag_AAC_6_1,
        kAudioChannelLayoutTag_Logic_6_1_B = (199 << 16) | 7,
        kAudioChannelLayoutTag_Logic_6_1_C = kAudioChannelLayoutTag_MPEG_6_1_A,
        kAudioChannelLayoutTag_Logic_6_1_D = (200 << 16) | 7,
        kAudioChannelLayoutTag_Logic_7_1_A = kAudioChannelLayoutTag_AudioUnit_7_1,
        kAudioChannelLayoutTag_Logic_7_1_B = (201 << 16) | 8,
        kAudioChannelLayoutTag_Logic_7_1_C = kAudioChannelLayoutTag_MPEG_7_1_C,
        kAudioChannelLayoutTag_Logic_7_1_SDDS_A = kAudioChannelLayoutTag_MPEG_7_1_A,
        kAudioChannelLayoutTag_Logic_7_1_SDDS_B = kAudioChannelLayoutTag_MPEG_7_1_B,
        kAudioChannelLayoutTag_Logic_7_1_SDDS_C = kAudioChannelLayoutTag_Emagic_Default_7_1,
        kAudioChannelLayoutTag_Logic_Atmos_5_1_2 = kAudioChannelLayoutTag_Atmos_5_1_2,
        kAudioChannelLayoutTag_Logic_Atmos_5_1_4 = kAudioChannelLayoutTag_Atmos_5_1_4,
        kAudioChannelLayoutTag_Logic_Atmos_7_1_2 = kAudioChannelLayoutTag_Atmos_7_1_2,
        kAudioChannelLayoutTag_Logic_Atmos_7_1_4_A = kAudioChannelLayoutTag_Atmos_7_1_4,
        kAudioChannelLayoutTag_Logic_Atmos_7_1_4_B = (202 << 16) | 12,
        kAudioChannelLayoutTag_Logic_Atmos_7_1_6 = (203 << 16) | 14,
        kAudioChannelLayoutTag_DiscreteInOrder = (147 << 16) | 0,
        kAudioChannelLayoutTag_CICP_1 = kAudioChannelLayoutTag_MPEG_1_0,
        kAudioChannelLayoutTag_CICP_2 = kAudioChannelLayoutTag_MPEG_2_0,
        kAudioChannelLayoutTag_CICP_3 = kAudioChannelLayoutTag_MPEG_3_0_A,
        kAudioChannelLayoutTag_CICP_4 = kAudioChannelLayoutTag_MPEG_4_0_A,
        kAudioChannelLayoutTag_CICP_5 = kAudioChannelLayoutTag_MPEG_5_0_A,
        kAudioChannelLayoutTag_CICP_6 = kAudioChannelLayoutTag_MPEG_5_1_A,
        kAudioChannelLayoutTag_CICP_7 = kAudioChannelLayoutTag_MPEG_7_1_B,
        kAudioChannelLayoutTag_CICP_9 = kAudioChannelLayoutTag_ITU_2_1,
        kAudioChannelLayoutTag_CICP_10 = kAudioChannelLayoutTag_ITU_2_2,
        kAudioChannelLayoutTag_CICP_11 = kAudioChannelLayoutTag_MPEG_6_1_A,
        kAudioChannelLayoutTag_CICP_12 = kAudioChannelLayoutTag_MPEG_7_1_C,
        kAudioChannelLayoutTag_CICP_13 = (204 << 16) | 24,
        kAudioChannelLayoutTag_CICP_14 = (205 << 16) | 8,
        kAudioChannelLayoutTag_CICP_15 = (206 << 16) | 12,
        kAudioChannelLayoutTag_CICP_16 = (207 << 16) | 10,
        kAudioChannelLayoutTag_CICP_17 = (208 << 16) | 12,
        kAudioChannelLayoutTag_CICP_18 = (209 << 16) | 14,
        kAudioChannelLayoutTag_CICP_19 = (210 << 16) | 12,
        kAudioChannelLayoutTag_CICP_20 = (211 << 16) | 14,
        kAudioChannelLayoutTag_BeginReserved = 0xF0000000,
        kAudioChannelLayoutTag_EndReserved = 0xFFFEFFFF,
        kAudioChannelLayoutTag_Unknown = 0xFFFF0000,
    }
);

extern_struct!(
    pub struct AudioChannelDescription {
        pub mChannelLabel: AudioChannelLabel,
        pub mChannelFlags: AudioChannelFlags,
        pub mCoordinates: [f32; 3],
    }
);

extern_struct!(
    pub struct AudioChannelLayout {
        pub mChannelLayoutTag: AudioChannelLayoutTag,
        pub mChannelBitmap: AudioChannelBitmap,
        pub mNumberChannelDescriptions: u32,
        pub mChannelDescriptions: [AudioChannelDescription; 1],
    }
);

inline_fn!(
    pub unsafe fn AudioChannelLayoutTag_GetNumberOfChannels(
        in_layout_tag: AudioChannelLayoutTag,
    ) -> u32 {
        todo!()
    }
);

extern_struct!(
    pub struct AudioFormatListItem {
        pub mASBD: AudioStreamBasicDescription,
        pub mChannelLayoutTag: AudioChannelLayoutTag,
    }
);

ns_enum!(
    #[underlying(c_long)]
    pub enum MPEG4ObjectID {
        kMPEG4Object_AAC_Main = 1,
        kMPEG4Object_AAC_LC = 2,
        kMPEG4Object_AAC_SSR = 3,
        kMPEG4Object_AAC_LTP = 4,
        kMPEG4Object_AAC_SBR = 5,
        kMPEG4Object_AAC_Scalable = 6,
        kMPEG4Object_TwinVQ = 7,
        kMPEG4Object_CELP = 8,
        kMPEG4Object_HVXC = 9,
    }
);
