//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
#![allow(unused_imports)]
#![allow(deprecated)]
#[path = "AudioSessionTypes.rs"]
mod __AudioSessionTypes;
#[path = "CoreAudioBaseTypes.rs"]
mod __CoreAudioBaseTypes;

pub use self::__AudioSessionTypes::AVAudioInteger;
pub use self::__AudioSessionTypes::AVAudioUInteger;
pub use self::__AudioSessionTypes::AudioSessionID;
pub use self::__AudioSessionTypes::{
    AVAudioSessionErrorCode, AVAudioSessionErrorCodeBadParam,
    AVAudioSessionErrorCodeCannotInterruptOthers, AVAudioSessionErrorCodeCannotStartPlaying,
    AVAudioSessionErrorCodeCannotStartRecording, AVAudioSessionErrorCodeExpiredSession,
    AVAudioSessionErrorCodeIncompatibleCategory, AVAudioSessionErrorCodeInsufficientPriority,
    AVAudioSessionErrorCodeIsBusy, AVAudioSessionErrorCodeMediaServicesFailed,
    AVAudioSessionErrorCodeMissingEntitlement, AVAudioSessionErrorCodeNone,
    AVAudioSessionErrorCodeResourceNotAvailable, AVAudioSessionErrorCodeSessionNotActive,
    AVAudioSessionErrorCodeSiriIsRecording, AVAudioSessionErrorCodeUnspecified,
};
pub use self::__CoreAudioBaseTypes::kAudioStreamAnyRate;
pub use self::__CoreAudioBaseTypes::AudioBuffer;
pub use self::__CoreAudioBaseTypes::AudioBufferList;
pub use self::__CoreAudioBaseTypes::AudioChannelDescription;
pub use self::__CoreAudioBaseTypes::AudioChannelLabel;
pub use self::__CoreAudioBaseTypes::AudioChannelLayout;
pub use self::__CoreAudioBaseTypes::AudioChannelLayoutTag;
pub use self::__CoreAudioBaseTypes::AudioClassDescription;
pub use self::__CoreAudioBaseTypes::AudioFormatFlags;
pub use self::__CoreAudioBaseTypes::AudioFormatID;
pub use self::__CoreAudioBaseTypes::AudioFormatListItem;
pub use self::__CoreAudioBaseTypes::AudioSampleType;
pub use self::__CoreAudioBaseTypes::AudioStreamBasicDescription;
pub use self::__CoreAudioBaseTypes::AudioStreamPacketDescription;
pub use self::__CoreAudioBaseTypes::AudioTimeStamp;
pub use self::__CoreAudioBaseTypes::AudioUnitSampleType;
pub use self::__CoreAudioBaseTypes::AudioValueRange;
pub use self::__CoreAudioBaseTypes::AudioValueTranslation;
pub use self::__CoreAudioBaseTypes::SMPTETime;
pub use self::__CoreAudioBaseTypes::{
    kAppleLosslessFormatFlag_16BitSourceData, kAppleLosslessFormatFlag_20BitSourceData,
    kAppleLosslessFormatFlag_24BitSourceData, kAppleLosslessFormatFlag_32BitSourceData,
    kAudioFormatFlagIsAlignedHigh, kAudioFormatFlagIsBigEndian, kAudioFormatFlagIsFloat,
    kAudioFormatFlagIsNonInterleaved, kAudioFormatFlagIsNonMixable, kAudioFormatFlagIsPacked,
    kAudioFormatFlagIsSignedInteger, kAudioFormatFlagsAreAllClear,
    kLinearPCMFormatFlagIsAlignedHigh, kLinearPCMFormatFlagIsBigEndian,
    kLinearPCMFormatFlagIsFloat, kLinearPCMFormatFlagIsNonInterleaved,
    kLinearPCMFormatFlagIsNonMixable, kLinearPCMFormatFlagIsPacked,
    kLinearPCMFormatFlagIsSignedInteger, kLinearPCMFormatFlagsAreAllClear,
    kLinearPCMFormatFlagsSampleFractionMask, kLinearPCMFormatFlagsSampleFractionShift,
};
pub use self::__CoreAudioBaseTypes::{
    kAudioChannelBit_Center, kAudioChannelBit_CenterSurround, kAudioChannelBit_CenterTopFront,
    kAudioChannelBit_CenterTopMiddle, kAudioChannelBit_CenterTopRear, kAudioChannelBit_LFEScreen,
    kAudioChannelBit_Left, kAudioChannelBit_LeftCenter, kAudioChannelBit_LeftSurround,
    kAudioChannelBit_LeftSurroundDirect, kAudioChannelBit_LeftTopFront,
    kAudioChannelBit_LeftTopMiddle, kAudioChannelBit_LeftTopRear, kAudioChannelBit_Right,
    kAudioChannelBit_RightCenter, kAudioChannelBit_RightSurround,
    kAudioChannelBit_RightSurroundDirect, kAudioChannelBit_RightTopFront,
    kAudioChannelBit_RightTopMiddle, kAudioChannelBit_RightTopRear, kAudioChannelBit_TopBackCenter,
    kAudioChannelBit_TopBackLeft, kAudioChannelBit_TopBackRight,
    kAudioChannelBit_TopCenterSurround, kAudioChannelBit_VerticalHeightCenter,
    kAudioChannelBit_VerticalHeightLeft, kAudioChannelBit_VerticalHeightRight, AudioChannelBitmap,
};
pub use self::__CoreAudioBaseTypes::{
    kAudioChannelCoordinates_Azimuth, kAudioChannelCoordinates_BackFront,
    kAudioChannelCoordinates_Distance, kAudioChannelCoordinates_DownUp,
    kAudioChannelCoordinates_Elevation, kAudioChannelCoordinates_LeftRight,
    AudioChannelCoordinateIndex,
};
pub use self::__CoreAudioBaseTypes::{
    kAudioChannelFlags_AllOff, kAudioChannelFlags_Meters,
    kAudioChannelFlags_RectangularCoordinates, kAudioChannelFlags_SphericalCoordinates,
    AudioChannelFlags,
};
pub use self::__CoreAudioBaseTypes::{
    kAudioChannelLabel_Ambisonic_W, kAudioChannelLabel_Ambisonic_X, kAudioChannelLabel_Ambisonic_Y,
    kAudioChannelLabel_Ambisonic_Z, kAudioChannelLabel_BeginReserved,
    kAudioChannelLabel_BinauralLeft, kAudioChannelLabel_BinauralRight, kAudioChannelLabel_Center,
    kAudioChannelLabel_CenterBottom, kAudioChannelLabel_CenterSurround,
    kAudioChannelLabel_CenterSurroundDirect, kAudioChannelLabel_CenterTopFront,
    kAudioChannelLabel_CenterTopMiddle, kAudioChannelLabel_CenterTopRear,
    kAudioChannelLabel_ClickTrack, kAudioChannelLabel_DialogCentricMix,
    kAudioChannelLabel_Discrete, kAudioChannelLabel_Discrete_0, kAudioChannelLabel_Discrete_1,
    kAudioChannelLabel_Discrete_10, kAudioChannelLabel_Discrete_11, kAudioChannelLabel_Discrete_12,
    kAudioChannelLabel_Discrete_13, kAudioChannelLabel_Discrete_14, kAudioChannelLabel_Discrete_15,
    kAudioChannelLabel_Discrete_2, kAudioChannelLabel_Discrete_3, kAudioChannelLabel_Discrete_4,
    kAudioChannelLabel_Discrete_5, kAudioChannelLabel_Discrete_6,
    kAudioChannelLabel_Discrete_65535, kAudioChannelLabel_Discrete_7,
    kAudioChannelLabel_Discrete_8, kAudioChannelLabel_Discrete_9, kAudioChannelLabel_EndReserved,
    kAudioChannelLabel_ForeignLanguage, kAudioChannelLabel_HOA_ACN, kAudioChannelLabel_HOA_ACN_0,
    kAudioChannelLabel_HOA_ACN_1, kAudioChannelLabel_HOA_ACN_10, kAudioChannelLabel_HOA_ACN_11,
    kAudioChannelLabel_HOA_ACN_12, kAudioChannelLabel_HOA_ACN_13, kAudioChannelLabel_HOA_ACN_14,
    kAudioChannelLabel_HOA_ACN_15, kAudioChannelLabel_HOA_ACN_2, kAudioChannelLabel_HOA_ACN_3,
    kAudioChannelLabel_HOA_ACN_4, kAudioChannelLabel_HOA_ACN_5, kAudioChannelLabel_HOA_ACN_6,
    kAudioChannelLabel_HOA_ACN_65024, kAudioChannelLabel_HOA_ACN_7, kAudioChannelLabel_HOA_ACN_8,
    kAudioChannelLabel_HOA_ACN_9, kAudioChannelLabel_HOA_N3D, kAudioChannelLabel_HOA_SN3D,
    kAudioChannelLabel_Haptic, kAudioChannelLabel_HeadphonesLeft,
    kAudioChannelLabel_HeadphonesRight, kAudioChannelLabel_HearingImpaired,
    kAudioChannelLabel_LFE2, kAudioChannelLabel_LFE3, kAudioChannelLabel_LFEScreen,
    kAudioChannelLabel_Left, kAudioChannelLabel_LeftBackSurround, kAudioChannelLabel_LeftBottom,
    kAudioChannelLabel_LeftCenter, kAudioChannelLabel_LeftEdgeOfScreen,
    kAudioChannelLabel_LeftSideSurround, kAudioChannelLabel_LeftSurround,
    kAudioChannelLabel_LeftSurroundDirect, kAudioChannelLabel_LeftTopFront,
    kAudioChannelLabel_LeftTopMiddle, kAudioChannelLabel_LeftTopRear,
    kAudioChannelLabel_LeftTopSurround, kAudioChannelLabel_LeftTotal, kAudioChannelLabel_LeftWide,
    kAudioChannelLabel_MS_Mid, kAudioChannelLabel_MS_Side, kAudioChannelLabel_Mono,
    kAudioChannelLabel_Narration, kAudioChannelLabel_Object, kAudioChannelLabel_RearSurroundLeft,
    kAudioChannelLabel_RearSurroundRight, kAudioChannelLabel_Right,
    kAudioChannelLabel_RightBackSurround, kAudioChannelLabel_RightBottom,
    kAudioChannelLabel_RightCenter, kAudioChannelLabel_RightEdgeOfScreen,
    kAudioChannelLabel_RightSideSurround, kAudioChannelLabel_RightSurround,
    kAudioChannelLabel_RightSurroundDirect, kAudioChannelLabel_RightTopFront,
    kAudioChannelLabel_RightTopMiddle, kAudioChannelLabel_RightTopRear,
    kAudioChannelLabel_RightTopSurround, kAudioChannelLabel_RightTotal,
    kAudioChannelLabel_RightWide, kAudioChannelLabel_TopBackCenter, kAudioChannelLabel_TopBackLeft,
    kAudioChannelLabel_TopBackRight, kAudioChannelLabel_TopCenterSurround,
    kAudioChannelLabel_Unknown, kAudioChannelLabel_Unused, kAudioChannelLabel_UseCoordinates,
    kAudioChannelLabel_VerticalHeightCenter, kAudioChannelLabel_VerticalHeightLeft,
    kAudioChannelLabel_VerticalHeightRight, kAudioChannelLabel_XY_X, kAudioChannelLabel_XY_Y,
};
pub use self::__CoreAudioBaseTypes::{
    kAudioChannelLayoutTag_AAC_3_0, kAudioChannelLayoutTag_AAC_4_0, kAudioChannelLayoutTag_AAC_5_0,
    kAudioChannelLayoutTag_AAC_5_1, kAudioChannelLayoutTag_AAC_6_0, kAudioChannelLayoutTag_AAC_6_1,
    kAudioChannelLayoutTag_AAC_7_0, kAudioChannelLayoutTag_AAC_7_1,
    kAudioChannelLayoutTag_AAC_7_1_B, kAudioChannelLayoutTag_AAC_7_1_C,
    kAudioChannelLayoutTag_AAC_Octagonal, kAudioChannelLayoutTag_AAC_Quadraphonic,
    kAudioChannelLayoutTag_AC3_1_0_1, kAudioChannelLayoutTag_AC3_2_1_1,
    kAudioChannelLayoutTag_AC3_3_0, kAudioChannelLayoutTag_AC3_3_0_1,
    kAudioChannelLayoutTag_AC3_3_1, kAudioChannelLayoutTag_AC3_3_1_1,
    kAudioChannelLayoutTag_Ambisonic_B_Format, kAudioChannelLayoutTag_Atmos_5_1_2,
    kAudioChannelLayoutTag_Atmos_5_1_4, kAudioChannelLayoutTag_Atmos_7_1_2,
    kAudioChannelLayoutTag_Atmos_7_1_4, kAudioChannelLayoutTag_Atmos_9_1_6,
    kAudioChannelLayoutTag_AudioUnit_4, kAudioChannelLayoutTag_AudioUnit_5,
    kAudioChannelLayoutTag_AudioUnit_5_0, kAudioChannelLayoutTag_AudioUnit_5_1,
    kAudioChannelLayoutTag_AudioUnit_6, kAudioChannelLayoutTag_AudioUnit_6_0,
    kAudioChannelLayoutTag_AudioUnit_6_1, kAudioChannelLayoutTag_AudioUnit_7_0,
    kAudioChannelLayoutTag_AudioUnit_7_0_Front, kAudioChannelLayoutTag_AudioUnit_7_1,
    kAudioChannelLayoutTag_AudioUnit_7_1_Front, kAudioChannelLayoutTag_AudioUnit_8,
    kAudioChannelLayoutTag_BeginReserved, kAudioChannelLayoutTag_Binaural,
    kAudioChannelLayoutTag_CICP_1, kAudioChannelLayoutTag_CICP_10, kAudioChannelLayoutTag_CICP_11,
    kAudioChannelLayoutTag_CICP_12, kAudioChannelLayoutTag_CICP_13, kAudioChannelLayoutTag_CICP_14,
    kAudioChannelLayoutTag_CICP_15, kAudioChannelLayoutTag_CICP_16, kAudioChannelLayoutTag_CICP_17,
    kAudioChannelLayoutTag_CICP_18, kAudioChannelLayoutTag_CICP_19, kAudioChannelLayoutTag_CICP_2,
    kAudioChannelLayoutTag_CICP_20, kAudioChannelLayoutTag_CICP_3, kAudioChannelLayoutTag_CICP_4,
    kAudioChannelLayoutTag_CICP_5, kAudioChannelLayoutTag_CICP_6, kAudioChannelLayoutTag_CICP_7,
    kAudioChannelLayoutTag_CICP_9, kAudioChannelLayoutTag_Cube, kAudioChannelLayoutTag_DTS_3_1,
    kAudioChannelLayoutTag_DTS_4_1, kAudioChannelLayoutTag_DTS_6_0_A,
    kAudioChannelLayoutTag_DTS_6_0_B, kAudioChannelLayoutTag_DTS_6_0_C,
    kAudioChannelLayoutTag_DTS_6_1_A, kAudioChannelLayoutTag_DTS_6_1_B,
    kAudioChannelLayoutTag_DTS_6_1_C, kAudioChannelLayoutTag_DTS_6_1_D,
    kAudioChannelLayoutTag_DTS_7_0, kAudioChannelLayoutTag_DTS_7_1,
    kAudioChannelLayoutTag_DTS_8_0_A, kAudioChannelLayoutTag_DTS_8_0_B,
    kAudioChannelLayoutTag_DTS_8_1_A, kAudioChannelLayoutTag_DTS_8_1_B,
    kAudioChannelLayoutTag_DVD_0, kAudioChannelLayoutTag_DVD_1, kAudioChannelLayoutTag_DVD_10,
    kAudioChannelLayoutTag_DVD_11, kAudioChannelLayoutTag_DVD_12, kAudioChannelLayoutTag_DVD_13,
    kAudioChannelLayoutTag_DVD_14, kAudioChannelLayoutTag_DVD_15, kAudioChannelLayoutTag_DVD_16,
    kAudioChannelLayoutTag_DVD_17, kAudioChannelLayoutTag_DVD_18, kAudioChannelLayoutTag_DVD_19,
    kAudioChannelLayoutTag_DVD_2, kAudioChannelLayoutTag_DVD_20, kAudioChannelLayoutTag_DVD_3,
    kAudioChannelLayoutTag_DVD_4, kAudioChannelLayoutTag_DVD_5, kAudioChannelLayoutTag_DVD_6,
    kAudioChannelLayoutTag_DVD_7, kAudioChannelLayoutTag_DVD_8, kAudioChannelLayoutTag_DVD_9,
    kAudioChannelLayoutTag_DiscreteInOrder, kAudioChannelLayoutTag_EAC3_6_1_A,
    kAudioChannelLayoutTag_EAC3_6_1_B, kAudioChannelLayoutTag_EAC3_6_1_C,
    kAudioChannelLayoutTag_EAC3_7_1_A, kAudioChannelLayoutTag_EAC3_7_1_B,
    kAudioChannelLayoutTag_EAC3_7_1_C, kAudioChannelLayoutTag_EAC3_7_1_D,
    kAudioChannelLayoutTag_EAC3_7_1_E, kAudioChannelLayoutTag_EAC3_7_1_F,
    kAudioChannelLayoutTag_EAC3_7_1_G, kAudioChannelLayoutTag_EAC3_7_1_H,
    kAudioChannelLayoutTag_EAC_6_0_A, kAudioChannelLayoutTag_EAC_7_0_A,
    kAudioChannelLayoutTag_Emagic_Default_7_1, kAudioChannelLayoutTag_EndReserved,
    kAudioChannelLayoutTag_HOA_ACN_N3D, kAudioChannelLayoutTag_HOA_ACN_SN3D,
    kAudioChannelLayoutTag_Hexagonal, kAudioChannelLayoutTag_ITU_1_0,
    kAudioChannelLayoutTag_ITU_2_0, kAudioChannelLayoutTag_ITU_2_1, kAudioChannelLayoutTag_ITU_2_2,
    kAudioChannelLayoutTag_ITU_3_0, kAudioChannelLayoutTag_ITU_3_1, kAudioChannelLayoutTag_ITU_3_2,
    kAudioChannelLayoutTag_ITU_3_2_1, kAudioChannelLayoutTag_ITU_3_4_1,
    kAudioChannelLayoutTag_Logic_4_0_A, kAudioChannelLayoutTag_Logic_4_0_B,
    kAudioChannelLayoutTag_Logic_4_0_C, kAudioChannelLayoutTag_Logic_5_0_A,
    kAudioChannelLayoutTag_Logic_5_0_B, kAudioChannelLayoutTag_Logic_5_0_C,
    kAudioChannelLayoutTag_Logic_5_0_D, kAudioChannelLayoutTag_Logic_5_1_A,
    kAudioChannelLayoutTag_Logic_5_1_B, kAudioChannelLayoutTag_Logic_5_1_C,
    kAudioChannelLayoutTag_Logic_5_1_D, kAudioChannelLayoutTag_Logic_6_0_A,
    kAudioChannelLayoutTag_Logic_6_0_B, kAudioChannelLayoutTag_Logic_6_0_C,
    kAudioChannelLayoutTag_Logic_6_1_A, kAudioChannelLayoutTag_Logic_6_1_B,
    kAudioChannelLayoutTag_Logic_6_1_C, kAudioChannelLayoutTag_Logic_6_1_D,
    kAudioChannelLayoutTag_Logic_7_1_A, kAudioChannelLayoutTag_Logic_7_1_B,
    kAudioChannelLayoutTag_Logic_7_1_C, kAudioChannelLayoutTag_Logic_7_1_SDDS_A,
    kAudioChannelLayoutTag_Logic_7_1_SDDS_B, kAudioChannelLayoutTag_Logic_7_1_SDDS_C,
    kAudioChannelLayoutTag_Logic_Atmos_5_1_2, kAudioChannelLayoutTag_Logic_Atmos_5_1_4,
    kAudioChannelLayoutTag_Logic_Atmos_7_1_2, kAudioChannelLayoutTag_Logic_Atmos_7_1_4_A,
    kAudioChannelLayoutTag_Logic_Atmos_7_1_4_B, kAudioChannelLayoutTag_Logic_Atmos_7_1_6,
    kAudioChannelLayoutTag_Logic_Mono, kAudioChannelLayoutTag_Logic_Quadraphonic,
    kAudioChannelLayoutTag_Logic_Stereo, kAudioChannelLayoutTag_MPEG_1_0,
    kAudioChannelLayoutTag_MPEG_2_0, kAudioChannelLayoutTag_MPEG_3_0_A,
    kAudioChannelLayoutTag_MPEG_3_0_B, kAudioChannelLayoutTag_MPEG_4_0_A,
    kAudioChannelLayoutTag_MPEG_4_0_B, kAudioChannelLayoutTag_MPEG_5_0_A,
    kAudioChannelLayoutTag_MPEG_5_0_B, kAudioChannelLayoutTag_MPEG_5_0_C,
    kAudioChannelLayoutTag_MPEG_5_0_D, kAudioChannelLayoutTag_MPEG_5_1_A,
    kAudioChannelLayoutTag_MPEG_5_1_B, kAudioChannelLayoutTag_MPEG_5_1_C,
    kAudioChannelLayoutTag_MPEG_5_1_D, kAudioChannelLayoutTag_MPEG_6_1_A,
    kAudioChannelLayoutTag_MPEG_7_1_A, kAudioChannelLayoutTag_MPEG_7_1_B,
    kAudioChannelLayoutTag_MPEG_7_1_C, kAudioChannelLayoutTag_MatrixStereo,
    kAudioChannelLayoutTag_MidSide, kAudioChannelLayoutTag_Mono, kAudioChannelLayoutTag_Octagonal,
    kAudioChannelLayoutTag_Pentagonal, kAudioChannelLayoutTag_Quadraphonic,
    kAudioChannelLayoutTag_SMPTE_DTV, kAudioChannelLayoutTag_Stereo,
    kAudioChannelLayoutTag_StereoHeadphones, kAudioChannelLayoutTag_TMH_10_2_full,
    kAudioChannelLayoutTag_TMH_10_2_std, kAudioChannelLayoutTag_Unknown,
    kAudioChannelLayoutTag_UseChannelBitmap, kAudioChannelLayoutTag_UseChannelDescriptions,
    kAudioChannelLayoutTag_WAVE_2_1, kAudioChannelLayoutTag_WAVE_3_0,
    kAudioChannelLayoutTag_WAVE_4_0_A, kAudioChannelLayoutTag_WAVE_4_0_B,
    kAudioChannelLayoutTag_WAVE_5_0_A, kAudioChannelLayoutTag_WAVE_5_0_B,
    kAudioChannelLayoutTag_WAVE_5_1_A, kAudioChannelLayoutTag_WAVE_5_1_B,
    kAudioChannelLayoutTag_WAVE_6_1, kAudioChannelLayoutTag_WAVE_7_1, kAudioChannelLayoutTag_XY,
};
pub use self::__CoreAudioBaseTypes::{
    kAudioFormat60958AC3, kAudioFormatAC3, kAudioFormatAES3, kAudioFormatALaw, kAudioFormatAMR,
    kAudioFormatAMR_WB, kAudioFormatAppleIMA4, kAudioFormatAppleLossless, kAudioFormatAudible,
    kAudioFormatDVIIntelIMA, kAudioFormatEnhancedAC3, kAudioFormatFLAC, kAudioFormatLinearPCM,
    kAudioFormatMACE3, kAudioFormatMACE6, kAudioFormatMIDIStream, kAudioFormatMPEG4AAC,
    kAudioFormatMPEG4AAC_ELD, kAudioFormatMPEG4AAC_ELD_SBR, kAudioFormatMPEG4AAC_ELD_V2,
    kAudioFormatMPEG4AAC_HE, kAudioFormatMPEG4AAC_HE_V2, kAudioFormatMPEG4AAC_LD,
    kAudioFormatMPEG4AAC_Spatial, kAudioFormatMPEG4CELP, kAudioFormatMPEG4HVXC,
    kAudioFormatMPEG4TwinVQ, kAudioFormatMPEGD_USAC, kAudioFormatMPEGLayer1,
    kAudioFormatMPEGLayer2, kAudioFormatMPEGLayer3, kAudioFormatMicrosoftGSM, kAudioFormatOpus,
    kAudioFormatParameterValueStream, kAudioFormatQDesign, kAudioFormatQDesign2,
    kAudioFormatQUALCOMM, kAudioFormatTimeCode, kAudioFormatULaw, kAudioFormatiLBC,
};
pub use self::__CoreAudioBaseTypes::{
    kAudioFormatFlagsAudioUnitCanonical, kAudioFormatFlagsCanonical, kAudioFormatFlagsNativeEndian,
    kAudioFormatFlagsNativeFloatPacked,
};
pub use self::__CoreAudioBaseTypes::{
    kAudioTimeStampHostTimeValid, kAudioTimeStampNothingValid, kAudioTimeStampRateScalarValid,
    kAudioTimeStampSMPTETimeValid, kAudioTimeStampSampleHostTimeValid,
    kAudioTimeStampSampleTimeValid, kAudioTimeStampWordClockTimeValid, AudioTimeStampFlags,
};
pub use self::__CoreAudioBaseTypes::{
    kAudio_BadFilePathError, kAudio_FileNotFoundError, kAudio_FilePermissionError,
    kAudio_MemFullError, kAudio_ParamError, kAudio_TooManyFilesOpenError,
    kAudio_UnimplementedError,
};
pub use self::__CoreAudioBaseTypes::{
    kMPEG4Object_AAC_LC, kMPEG4Object_AAC_LTP, kMPEG4Object_AAC_Main, kMPEG4Object_AAC_SBR,
    kMPEG4Object_AAC_SSR, kMPEG4Object_AAC_Scalable, kMPEG4Object_CELP, kMPEG4Object_HVXC,
    kMPEG4Object_TwinVQ, MPEG4ObjectID,
};
pub use self::__CoreAudioBaseTypes::{
    kSMPTETimeRunning, kSMPTETimeUnknown, kSMPTETimeValid, SMPTETimeFlags,
};
pub use self::__CoreAudioBaseTypes::{
    kSMPTETimeType2398, kSMPTETimeType24, kSMPTETimeType25, kSMPTETimeType2997,
    kSMPTETimeType2997Drop, kSMPTETimeType30, kSMPTETimeType30Drop, kSMPTETimeType50,
    kSMPTETimeType5994, kSMPTETimeType5994Drop, kSMPTETimeType60, kSMPTETimeType60Drop,
    SMPTETimeType,
};
